In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
df=pd.read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

In [2]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,NaN,0.0,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN

In [3]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,4.990300e+04,52620.000000,51824.000000,4.090200e+04,52620.000000,51824.000000,49634.000000,52556.000000,51759.000000,40648.000000,...,47025.000000,31353.000000,47631.000000,49359.000000,37133.000000,36656.000000,22477.000000,42939.000000,52544.000000,45977.000000
mean,1.444824e+05,1714.861250,1685.322187,6.334352e+03,44.938902,44.869162,2664.428872,32.615493,31.513007,87.924709,...,20723.822670,12.329171,252.150339,8.057785,10.767659,32.641908,52.214852,3.096139,73.968148,0.723143
std,1.449007e+06,15594.434808,15177.039439,5.133953e+04,373.756853,362.639731,5249.072293,116.190395,81.315878,172.321518,...,20353.318717,19.361248,117.410103,4.161356,10.474468,13.443972,31.633129,2.517995,7.390752,0.153142
min,1.000000e+00,-8261.000000,-552.000000,1.000000e+00,-1918.000000,-232.143000,0.001000,-2212.545000,-269.978000,0.000000,...,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.280000,0.354000
25%,1.500000e+02,0.000000,0.714000,1.100000e+01,0.000000,0.000000,77.858000,0.000000,0.218000,3.551000,...,5338.454000,0.500000,155.898000,5.310000,1.900000,21.400000,21.222000,1.300000,69.870000,0.601000
50%,1.824000e+03,13.000000,17.857000,7.600000e+01,0.000000,0.286000,515.518500,1.972500,3.584000,18.556000,...,14048.881000,2.000000,238.339000,7.110000,6.400000,31.400000,52.232000,2.500000,75.400000,0.754000
75%,1.831850e+04,206.000000,214.429000,6.387500e+02,3.000000,3.571000,2975.580750,22.956000,25.956500,76.361000,...,31400.840000,18.100000,318.991000,10.390000,19.600000,40.900000,83.741000,4.200000,79.380000,0.847000
max,4.512060e+07,511285.000000,468804.000000,1.182408e+06,10491.000000,7456.857000,59108.264000,8652.658000,2472.188000,1237.551000,...,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,98.999000,13.800000,86.750000,0.953000

In [4]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index'],
      dtype='object')

In [5]:
df.dtypes

iso_code                               object
continent                              object
location                               object
date                                   object
total_cases                           float64
new_cases                             float64
new_cases_smoothed                    float64
total_deaths                          float64
new_deaths                            float64
new_deaths_smoothed                   float64
total_cases_per_million               float64
new_cases_per_million                 float64
new_cases_smoothed_per_million        float64
total_deaths_per_million              float64
new_deaths_per_million                float64
new_deaths_smoothed_per_million       float64
icu_patients                          float64
icu_patients_per_million              float64
hosp_patients                         float64
hosp_patients_per_million             float64
weekly_icu_admissions                 float64
weekly_icu_admissions_per_million     float64
weekly_hosp_admissions                float64
weekly_hosp_admissions_per_million    float64
total_tests                           float64
new_tests                             float64
total_tests_per_thousand              float64
new_tests_per_thousand                float64
new_tests_smoothed                    float64
new_tests_smoothed_per_thousand       float64
tests_per_case                        float64
positive_rate                         float64
tests_units                            object
stringency_index                      float64
population                            float64
population_density                    float64
median_age                            float64
aged_65_older                         float64
aged_70_older                         float64
gdp_per_capita                        float64
extreme_poverty                       float64
cardiovasc_death_rate                 float64
diabetes_prevalence                   float64
female_smokers                        float64
male_smokers                          float64
handwashing_facilities                float64
hospital_beds_per_thousand            float64
life_expectancy                       float64
human_development_index               float64
dtype: object

In [31]:
df=df.fillna('0')
country=['India','Italy','Spain']
features = ['total_cases', 'new_cases',
       'new_cases_smoothed', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index']
X =  df[features]
y = df.total_deaths
# X = X.select_dtypes(exclude=['object'])
# print(X.isnull().sum())
print(X.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0)

(53530, 43)

In [34]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
model =  DecisionTreeRegressor(random_state=0)
model.fit(X_train,y_train)
predicted_val_of_y = model.predict(X_test)
print(f'predicted_val_of_y ={predicted_val_of_y[0:4]}')
mae = mean_absolute_error(y_test,predicted_val_of_y)
print(f'MAE = {mae}')

predicted_val_of_y =[ 229.  603. 6399. 1280.]
MAE = 81.56809265832244

In [35]:
y_test.head(4)

22023     229
3415      605
38258    6408
41454    1356
Name: total_deaths, dtype: object

In [36]:
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0,shuffle = False)
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
model =  DecisionTreeRegressor(random_state=0)
model.fit(X_train_s,y_train_s)
predicted_val_of_y_s = model.predict(X_test_s)
print(f'predicted_val_of_y ={predicted_val_of_y[0:4]}')
mae = mean_absolute_error(y_test,predicted_val_of_y_s)
print(f'MAE = {mae}')

predicted_val_of_y =[ 229.  603. 6399. 1280.]
MAE = 8992.705025219502

In [37]:
y_test_s.head(4)

42824    27
42825    27
42826    27
42827    27
Name: total_deaths, dtype: object